<?php

use Illuminate\Database\Seeder;

class PeopleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('people')->delete();
        
        \DB::table('people')->insert(array (
            0 => 
            array (
                'id' => 1,
                'alias' => 'president',
                'category' => 'professors',
                'rank' => 'president',
                'fullname' => 'Πρόεδρος Τμήματος',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-27 15:06:55',
                'updated_at' => '2017-03-24 14:10:05',
            ),
            1 => 
            array (
                'id' => 2,
                'alias' => 'geoatsi-president',
                'category' => 'professors',
                'rank' => 'president',
                'fullname' => 'Τσιχριντζής Γεώργιος ',
                'tags' => 'τσιχριντζης γεωργιος γιωργος tsixrintzis τσιχριτζης tsixritzis',
                'avatar' => 'geoatsi.jpg',
                'location' => '506, κεντρικό κτίριο',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142322',
                'email' => 'geoatsi@unipi.gr',
                'website' => 'http://www.unipi.gr/faculty/geoatsi',
                'divider' => '0',
                'created_at' => '2016-12-27 15:04:13',
                'updated_at' => '2017-03-30 17:06:36',
            ),
            2 => 
            array (
                'id' => 3,
                'alias' => 'professors',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Καθηγητές',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-27 15:06:55',
                'updated_at' => '2017-03-24 14:10:10',
            ),
            3 => 
            array (
                'id' => 5,
                'alias' => 'mvirvou',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Βίρβου Μαρία',
                'tags' => 'βιρβου μαρια birbou maria',
                'avatar' => 'mvirvou.jpg',
                'location' => '507, κεντρικό κτίριο',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142269',
                'email' => 'mvirvou@unipi.gr',
                'website' => 'http://www.unipi.gr/faculty/mvirvou',
                'divider' => '0',
                'created_at' => '2016-12-28 14:06:55',
                'updated_at' => '2017-02-18 14:05:43',
            ),
            4 => 
            array (
                'id' => 6,
                'alias' => 'fotis',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Γεωργιακώδης Φώτιος',
                'tags' => 'georgiakodis gewrgiakodis γεωργιακωδης φωτιος φωτης',
                'avatar' => 'default.jpg',
                'location' => '512, κεντρικό κτίριο	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142276	',
                'email' => 'fotis@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/georgiakodis/',
                'divider' => '0',
                'created_at' => '2016-12-28 14:06:55',
                'updated_at' => '2017-02-18 13:51:40',
            ),
            5 => 
            array (
                'id' => 7,
                'alias' => 'despotis',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Δεσπότης Δημήτριος',
                'tags' => 'dimitris dimitrios δεσποτης δημητριος δημητρης',
                'avatar' => 'despotis.jpg',
                'location' => '702, Γ. Λαμπράκη 126	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142411	',
                'email' => 'despotis@unipi.gr',
                'website' => 'https://sites.google.com/site/dimitrisdespotis/',
                'divider' => '0',
                'created_at' => '2016-12-28 14:15:41',
                'updated_at' => '2017-02-18 13:52:12',
            ),
            6 => 
            array (
                'id' => 8,
                'alias' => 'cdoulig',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Δουληγέρης Χρήστος',
                'tags' => 'douligeris δουληγερης χρηστος xristos xrhstos',
                'avatar' => 'cdoulig.jpg',
                'location' => '302, κεντρικό κτίριο	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142137	',
                'email' => 'cdoulig@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 14:15:41',
                'updated_at' => '2017-02-18 13:52:35',
            ),
            7 => 
            array (
                'id' => 9,
                'alias' => 'ytheod',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Θεοδωρίδης Ιωάννης',
                'tags' => 'theodoridis θεοδωριδης γιαννης ιωαννης giannis ioannis yiannis',
                'avatar' => 'ytheod.jpg',
                'location' => '501, κεντρικό κτίριο	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142449	',
                'email' => 'ytheod@unipi.gr',
                'website' => 'http://www.unipi.gr/faculty/ytheod',
                'divider' => '0',
                'created_at' => '2016-12-28 14:22:19',
                'updated_at' => '2017-02-18 13:53:04',
            ),
            8 => 
            array (
                'id' => 10,
                'alias' => 'themisp',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Παναγιωτόπουλος Θεμιστοκλής',
                'tags' => 'panagiotopoulos παναγιωτοπουλος θεμιστοκλης θεμης themistoklis',
                'avatar' => 'themisp.jpg',
                'location' => '604, Γ. Λαμπράκη 126	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142146	',
                'email' => 'themisp@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 14:22:19',
                'updated_at' => '2017-02-18 13:53:34',
            ),
            9 => 
            array (
                'id' => 11,
                'alias' => 'arissap',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Σαπουνάκης Αριστείδης',
                'tags' => 'sapounakis σαπουνακης αριστειδης αρης aristidis aristeidis',
                'avatar' => 'default.jpg',
                'location' => '542, κεντρικό κτίριο	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142262	',
                'email' => 'arissap@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/sapounakis/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:07:42',
                'updated_at' => '2017-02-18 14:03:01',
            ),
            10 => 
            array (
                'id' => 12,
                'alias' => 'ysiskos',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Σίσκος Ιωάννης',
                'tags' => 'σισκος ιωαννης γιαννης ioannis giannis yiannis',
                'avatar' => 'ysiskos.jpg',
                'location' => '501, κεντρικό κτίριο',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142260	',
                'email' => 'ysiskos@unipi.gr',
                'website' => 'http://www.unipi.gr/faculty/ysiskos/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:07:42',
                'updated_at' => '2017-02-18 13:54:49',
            ),
            11 => 
            array (
                'id' => 13,
                'alias' => 'pgtsik',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Τσικούρας Παναγιώτης-Γεώργιος',
                'tags' => 'tsikouras τσικουρας παναγιωτης γεωργιος γιωργος',
                'avatar' => 'default.jpg',
                'location' => '542, κεντρικό κτίριο	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142262	',
                'email' => 'pgtsik@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/tsikouras/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:11:13',
                'updated_at' => '2017-02-18 13:55:15',
            ),
            12 => 
            array (
                'id' => 15,
                'alias' => 'associate-professors',
                'category' => 'professors',
                'rank' => 'associate-professors',
                'fullname' => 'Αναπληρωτές Καθηγητές',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-28 15:16:40',
                'updated_at' => '2017-03-24 14:10:58',
            ),
            13 => 
            array (
                'id' => 16,
                'alias' => 'dapost',
                'category' => 'professors',
                'rank' => 'associate-professors',
                'fullname' => 'Αποστόλου Δημήτριος',
                'tags' => 'apostolou αποστολου δημητριος δημητρης dimitrios dimitris mitsos μητσος',
                'avatar' => 'dapost.jpg',
                'location' => '303, Γ. Λαμπράκη 126	',
                'office_hours' => 'Τρίτη 12:00 - 14:00, Τετάρτη 12:00 - 14:00',
                'phone_number' => '+302104142476	',
                'email' => 'dapost@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:16:40',
                'updated_at' => '2017-02-18 13:56:28',
            ),
            14 => 
            array (
                'id' => 17,
                'alias' => 'vergados',
                'category' => 'professors',
                'rank' => 'associate-professors',
                'fullname' => 'Βέργαδος Δημήτριος',
                'tags' => 'βεργαδος δημητρης δημητριος dimitris dimitrios',
                'avatar' => 'vergados.jpg',
                'location' => '104, Γ. Λαμπράκη 126	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142479	',
                'email' => 'vergados@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:24:15',
                'updated_at' => '2017-02-18 14:02:32',
            ),
            15 => 
            array (
                'id' => 18,
                'alias' => 'kmetax',
                'category' => 'professors',
                'rank' => 'associate-professors',
                'fullname' => 'Μεταξιώτης Κωνσταντίνος',
                'tags' => 'metaksiotis μεταξιωτης κωνσταντινος κωστας ντινος kostas',
                'avatar' => 'kmetax.jpg',
                'location' => '303, Γ. Λαμπράκη 126	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142378',
                'email' => 'kmetax@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:24:15',
                'updated_at' => '2017-02-18 13:58:21',
            ),
            16 => 
            array (
                'id' => 19,
                'alias' => 'dpolemi',
                'category' => 'professors',
                'rank' => 'associate-professors',
                'fullname' => 'Πολέμη Δέσποινα',
                'tags' => 'despoina despina πολεμη δεσποινα',
                'avatar' => 'dpolemi.jpg',
                'location' => '502, κεντρικό κτίριο',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142270	',
                'email' => 'dpolemi@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:25:54',
                'updated_at' => '2017-02-18 13:59:25',
            ),
            17 => 
            array (
                'id' => 20,
                'alias' => 'assistant-professors',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Επίκουροι Καθηγητές',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-28 15:25:54',
                'updated_at' => '2017-03-24 14:11:08',
            ),
            18 => 
            array (
                'id' => 21,
                'alias' => 'avou',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Βουγιουκλίδου Άννα',
                'tags' => 'βουγιουκλιδου αννα anna ana vougiouklidou',
                'avatar' => 'avou.jpg',
                'location' => 'Ζέας 80-82, 4ος όροφος	',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142176	',
                'email' => 'avou@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/avou/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:30:06',
                'updated_at' => '2017-02-18 13:59:44',
            ),
            19 => 
            array (
                'id' => 22,
                'alias' => 'pkotzani',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Κοτζανικολάου Παναγιώτης',
                'tags' => 'κοτζανικολαου παναγιωτης panagiotis kotzanikolaou',
                'avatar' => 'pkotzani.jpg',
                'location' => '302, Γ. Λαμπράκη 126',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142123	',
                'email' => 'pkotzani@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/pkotzani/index.php/gr/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:30:06',
                'updated_at' => '2017-02-18 14:02:11',
            ),
            20 => 
            array (
                'id' => 23,
                'alias' => 'konstant',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Κωνσταντόπουλος Χαράλαμπος',
                'tags' => 'κωνσταντοπουλος χαραλαμπος xaralampos',
                'avatar' => 'konstant.jpg',
                'location' => '301, Γ. Λαμπράκη 126	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 21 04142124',
                'email' => 'konstant@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/konstantopoulos/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:36:38',
                'updated_at' => '2017-02-18 14:04:00',
            ),
            21 => 
            array (
                'id' => 24,
                'alias' => 'pikrakis',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Πικράκης Άγγελος',
                'tags' => 'aggelos αγγελος πικρακης',
                'avatar' => 'pikrakis.jpeg',
                'location' => '505, κεντρικό κτίριο	',
                'office_hours' => 'Τρίτη 16:00 - 18:00',
                'phone_number' => '+30 210 4142128	',
                'email' => 'pikrakis@unipi.gr',
                'website' => 'https://sites.google.com/site/aggelospikrakis/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:36:38',
                'updated_at' => '2017-02-18 14:04:22',
            ),
            22 => 
            array (
                'id' => 25,
                'alias' => 'mpsarak',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Ψαράκης Μιχαήλ',
                'tags' => 'psarakis ψαρακης μιχαηλ μιχαλης mixalis',
                'avatar' => 'mpsarak.jpg',
                'location' => '302, Γ. Λαμπράκη 126',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142425	',
                'email' => 'mpsarak@unipi.gr',
                'website' => 'http://www.cs.unipi.gr/psarakis/',
                'divider' => '0',
                'created_at' => '2016-12-28 15:39:50',
                'updated_at' => '2017-02-18 14:04:40',
            ),
            23 => 
            array (
                'id' => 27,
                'alias' => 'talepis',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Αλέπης Ευθύμιος',
                'tags' => 'αλεπης ευθυμιος tim euthimios efthimios',
                'avatar' => 'talepis.jpg',
                'location' => '540, κεντρικό κτίριο	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142311',
                'email' => 'talepis@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:44:47',
                'updated_at' => '2017-02-18 14:12:25',
            ),
            24 => 
            array (
                'id' => 28,
                'alias' => 'kpatsak',
                'category' => 'professors',
                'rank' => 'assistant-professors',
                'fullname' => 'Πατσάκης Κωνσταντίνος',
                'tags' => 'patsakis πατσακης κωνσταντινος κωστας kostas konstantinos',
                'avatar' => 'kpatsak.jpg',
                'location' => '540, κεντρικό κτίριο	',
                'office_hours' => '16:00 - 18:00',
                'phone_number' => '+30 210 4142261',
                'email' => 'kpatsak@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:44:47',
                'updated_at' => '2017-02-18 14:12:50',
            ),
            25 => 
            array (
                'id' => 29,
                'alias' => 'professors-emeriti',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Ομότιμοι Καθηγητές',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-28 15:51:55',
                'updated_at' => '2017-03-24 14:11:02',
            ),
            26 => 
            array (
                'id' => 30,
                'alias' => 'aleksandr',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Αλεξανδρής Νικόλαος',
                'tags' => 'alexandris αλεξανδρης νικολαος νικος nikos nikolaos',
                'avatar' => 'aleksandr.jpg',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => 'aleksandr@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:51:55',
                'updated_at' => '2017-02-18 14:13:15',
            ),
            27 => 
            array (
                'id' => 31,
                'alias' => 'mgeor',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Γεωργιακόδης Μιχαήλ',
                'tags' => 'georgiakodis γεωργιακοδης μιχαηλ μιχαλης mixalis',
                'avatar' => 'default.jpg',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => 'mgeor@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 15:53:23',
                'updated_at' => '2017-02-18 14:13:33',
            ),
            28 => 
            array (
                'id' => 34,
                'alias' => 'antonios',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Παναγιωτόπουλος Αντώνιος',
                'tags' => 'παναγιωτοπουλος αντωνιος panagiotopoulos',
                'avatar' => 'antonios.jpg',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => 'antonios@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 16:15:25',
                'updated_at' => '2017-02-18 14:13:59',
            ),
            29 => 
            array (
                'id' => 35,
                'alias' => 'jcp',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Παναγιωτόπουλος Ιωάννης-Χρήστος',
                'tags' => 'panagiotopoulos ioannis yiannis giannis ιωαννης παναγιωτοπουλος χρηστος xristos john chris',
                'avatar' => 'default.jpg',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => 'jcp@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 16:15:25',
                'updated_at' => '2017-02-18 14:14:31',
            ),
            30 => 
            array (
                'id' => 36,
                'alias' => 'efountas',
                'category' => 'professors',
                'rank' => 'professors-emeriti',
                'fullname' => 'Φούντας Ευάγγελος',
                'tags' => 'foudas fountas φουντας ευαγγελος βαγγελης evaggelos euagellos vaggelis',
                'avatar' => 'default.jpg',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => 'efountas@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-28 16:16:06',
                'updated_at' => '2017-02-18 14:14:52',
            ),
            31 => 
            array (
                'id' => 37,
                'alias' => 'lecturers',
                'category' => 'professors',
                'rank' => 'lecturers',
                'fullname' => 'Λέκτορες',
                'tags' => '',
                'avatar' => '',
                'location' => NULL,
                'office_hours' => NULL,
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'divider' => '1',
                'created_at' => '2016-12-29 02:12:20',
                'updated_at' => '2017-03-24 14:11:05',
            ),
            32 => 
            array (
                'id' => 38,
                'alias' => 'bgotsi',
                'category' => 'secretariat',
                'rank' => 'secretariat',
                'fullname' => 'Γκότση Βασιλική',
                'tags' => 'γκοτση βασιλικη vasiliki basiliki',
                'avatar' => 'default.jpg',
                'location' => 'Ζέας 80-82	',
                'office_hours' => NULL,
                'phone_number' => '+30 210 4142097	',
                'email' => 'bgotsi@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-29 16:08:56',
                'updated_at' => '2017-02-18 14:15:17',
            ),
            33 => 
            array (
                'id' => 39,
                'alias' => 'aristeakats',
                'category' => 'secretariat',
                'rank' => 'secretariat',
                'fullname' => 'Κατσιαδράμη Αριστέα',
                'tags' => 'katsiadrami κατσιαδραμη αριστεα',
                'avatar' => 'default.jpg',
                'location' => 'Ζέας 80-82	',
                'office_hours' => NULL,
                'phone_number' => '+30 210 4142067	',
                'email' => 'aristeakats@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-29 16:11:17',
                'updated_at' => '2017-02-18 14:15:32',
            ),
            34 => 
            array (
                'id' => 40,
                'alias' => 'rouvali',
                'category' => 'secretariat',
                'rank' => 'secretariat',
                'fullname' => 'Ρούβαλη Θεοδώρα',
                'tags' => 'theodora ρουβαλη θεοδωρα',
                'avatar' => 'default.jpg',
                'location' => 'Ζέας 80-82	',
                'office_hours' => NULL,
                'phone_number' => '+30 210 4142437	',
                'email' => 'rouvali@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2016-12-29 16:11:17',
                'updated_at' => '2017-02-18 14:15:49',
            ),
            35 => 
            array (
                'id' => 136,
                'alias' => 'assinik',
                'category' => 'professors',
                'rank' => 'professors',
                'fullname' => 'Ασημακόπουλος Νικήτας ',
                'tags' => 'asimakopoulos nikitas nikhtas ασημακοπουλος νικητας ashmakopoulos',
                'avatar' => 'assinik.jpg',
                'location' => '308, κεντρικό κτίριο',
                'office_hours' => '16:00-18:00',
                'phone_number' => '+30 210 4142145',
                'email' => 'assinik@unipi.gr',
                'website' => NULL,
                'divider' => '0',
                'created_at' => '2017-03-30 17:00:30',
                'updated_at' => '2017-03-30 17:00:30',
            ),
        ));
        
        
    }
}
